# Generated by Django 5.1 on 2024-10-24 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0029_proxynode_native_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrongSwanConfig',
            fields=[
                ('proxy_node', models.OneToOneField(help_text='代理节点', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='strongswan_config', serialize=False, to='proxy.proxynode', verbose_name='代理节点')),
            ],
            options={
                'verbose_name': 'StrongSwan配置',
                'verbose_name_plural': 'StrongSwan配置',
            },
        ),
        migrations.AlterModelOptions(
            name='trojanconfig',
            options={'verbose_name': 'Trojan配置', 'verbose_name_plural': 'Trojan配置'},
        ),
        migrations.RenameIndex(
            model_name='usertrafficlog',
            new_name='proxy_usert_user_id_9c6495_idx',
            old_name='idx_user_proxy_node_created_at',
        ),
        migrations.AlterField(
            model_name='proxynode',
            name='ehco_listen_type',
            field=models.CharField(choices=[('raw', 'raw'), ('ws', 'ws'), ('wss', 'wss')], default='raw', max_length=64, verbose_name='隧道监听类型'),
        ),
        migrations.AlterField(
            model_name='proxynode',
            name='ehco_transport_type',
            field=models.CharField(choices=[('raw', 'raw'), ('ws', 'ws'), ('wss', 'wss')], default='raw', max_length=64, verbose_name='隧道传输类型'),
        ),
        migrations.AlterField(
            model_name='proxynode',
            name='node_type',
            field=models.CharField(choices=[('ss', 'ss'), ('trojan', 'trojan'), ('ssr', 'ssr'), ('vmess', 'vmess'), ('vless', 'vless'), ('strongswan', 'strongswan')], default='ss', max_length=32, verbose_name='节点类型'),
        ),
        migrations.AlterField(
            model_name='relayrule',
            name='listen_type',
            field=models.CharField(choices=[('raw', 'raw'), ('ws', 'ws'), ('wss', 'wss')], default='raw', max_length=64, verbose_name='监听类型'),
        ),
        migrations.AlterField(
            model_name='relayrule',
            name='transport_type',
            field=models.CharField(choices=[('raw', 'raw'), ('ws', 'ws'), ('wss', 'wss')], default='raw', max_length=64, verbose_name='传输类型'),
        ),
    ]
