# Generated by Django 5.1 on 2024-10-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0030_strongswanconfig_alter_trojanconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssconfig',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='strongswanconfig',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='trojanconfig',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='备注'),
        ),
    ]
