# Generated by Django 5.1 on 2024-10-24 15:25

import trix_editor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sspanel', '0022_alter_moneycode_number_alter_moneycode_user'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ticketmessage',
            new_name='sspanel_tic_ticket__bad3b3_idx',
            old_name='idx_ticket_created_at',
        ),
        migrations.RenameIndex(
            model_name='userorder',
            new_name='sspanel_use_user_id_423850_idx',
            old_name='idx_user_status',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='body',
            field=trix_editor.fields.TrixEditorField(verbose_name='主体'),
        ),
    ]
